name: Run Tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit).
  group: run_tests_${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0

      - name: "Setting up Python"
        uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # v2.3.3
        with:
          python-version: "3.8"

      - name: "Install"
        run: |
          pip install -e .
          pip install pytest==7.2.1

      - name: "Test"
        run: |
          pytest
